### ISSUE TITLE
Windows Phone 8 has problem with https JS url to get map data

### ISSUE THREAD

**Issue by jameswennmacher** [Jasig/MapPortlet#11]
See http://jasig.275507.n4.nabble.com/Maps-Portlet-and-Googlemaps-JS-URL-and-Windows-Phone-8-td4662704.html

I have been doing some work with the Maps Portlet.

mapView.jsp uses this url to link to Google Map's JS library :

https://maps.google.com/maps/api/js?sensor=true

However, this will not work on windows phone 8 and results in a hung or blank page as the global google object is left undefined.

Using the following URL does work on windows phone 8:

http://maps.googleapis.com/maps/api/js?sensor=true

---------------- update
Apologies, I didn't notice that the second URL used http instead of https. 
For some reason google maps blocks windows phone 8 if https is used, but of course we need to use https in our authenticated uPortal. 
I was just testing this on my desktop install before I posted here, hence why I didn't event notice that the second URL used http.

**Comment by ChristianMurphy** [comment]
Sounds like the issue has been resolved.
Feel free to reopen if the problem reappears.
